### ISSUE TITLE
Coding style!

### ISSUE THREAD

**Issue by greeny** [TonyVlcek/Maturita#1]
- use tabs
- use same formatting as in PHP
  - spaces between `do` and `{`
  - spaces between `while/if/...` and `(`
  - structs and functions should have `{` on new line
  - changing type with space after last brace (`(TPRVEK*) malloc(sizeof(TPRVEK))`)
- naming
  - use english OR czech, but not mixed
  - functions should start with lovercased letter
  - structs should start with uppercased letter and not be capitalized, also not prefixed by `T` (if you want prefix, use `T_`

**Comment by TonyVlcek** [comment]
This is an initial commit. I'm definitely going to set up some coding style.
Thank you for mentioning that.
